// Generated by gencpp from file cmrosutils/CMRemoteRequest.msg
// DO NOT EDIT!


#ifndef CMROSUTILS_MESSAGE_CMREMOTEREQUEST_H
#define CMROSUTILS_MESSAGE_CMREMOTEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cmrosutils
{
template <class ContainerAllocator>
struct CMRemoteRequest_
{
  typedef CMRemoteRequest_<ContainerAllocator> Type;

  CMRemoteRequest_()
    : type()
    , msg()
    , data()  {
    }
  CMRemoteRequest_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , msg(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CMRemoteRequest_

typedef ::cmrosutils::CMRemoteRequest_<std::allocator<void> > CMRemoteRequest;

typedef boost::shared_ptr< ::cmrosutils::CMRemoteRequest > CMRemoteRequestPtr;
typedef boost::shared_ptr< ::cmrosutils::CMRemoteRequest const> CMRemoteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cmrosutils::CMRemoteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cmrosutils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a20fcbf285ac8d5dda1e13b8bc92d134";
  }

  static const char* value(const ::cmrosutils::CMRemoteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa20fcbf285ac8d5dULL;
  static const uint64_t static_value2 = 0xda1e13b8bc92d134ULL;
};

template<class ContainerAllocator>
struct DataType< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cmrosutils/CMRemoteRequest";
  }

  static const char* value(const ::cmrosutils::CMRemoteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n\
string msg\n\
string data\n\
";
  }

  static const char* value(const ::cmrosutils::CMRemoteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.msg);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CMRemoteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmrosutils::CMRemoteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cmrosutils::CMRemoteRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CMROSUTILS_MESSAGE_CMREMOTEREQUEST_H
