// Generated by gencpp from file hellocm_msgs/InitResponse.msg
// DO NOT EDIT!


#ifndef HELLOCM_MSGS_MESSAGE_INITRESPONSE_H
#define HELLOCM_MSGS_MESSAGE_INITRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hellocm_msgs
{
template <class ContainerAllocator>
struct InitResponse_
{
  typedef InitResponse_<ContainerAllocator> Type;

  InitResponse_()
    : success(false)
    , cycletime(0)
    , message()  {
    }
  InitResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , cycletime(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _cycletime_type;
  _cycletime_type cycletime;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::hellocm_msgs::InitResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hellocm_msgs::InitResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitResponse_

typedef ::hellocm_msgs::InitResponse_<std::allocator<void> > InitResponse;

typedef boost::shared_ptr< ::hellocm_msgs::InitResponse > InitResponsePtr;
typedef boost::shared_ptr< ::hellocm_msgs::InitResponse const> InitResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hellocm_msgs::InitResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hellocm_msgs::InitResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hellocm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hellocm_msgs': ['/home/zz/carmaker_ros/ros/ros1_ws/src/hellocm_msgs/msg'], 'std_msgs': ['/opt/ros/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hellocm_msgs::InitResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hellocm_msgs::InitResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hellocm_msgs::InitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hellocm_msgs::InitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hellocm_msgs::InitResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hellocm_msgs::InitResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hellocm_msgs::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b782e011a181d0d03948ac040f0f5458";
  }

  static const char* value(const ::hellocm_msgs::InitResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb782e011a181d0d0ULL;
  static const uint64_t static_value2 = 0x3948ac040f0f5458ULL;
};

template<class ContainerAllocator>
struct DataType< ::hellocm_msgs::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hellocm_msgs/InitResponse";
  }

  static const char* value(const ::hellocm_msgs::InitResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hellocm_msgs::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool   success\n\
int32  cycletime\n\
string message\n\
\n\
";
  }

  static const char* value(const ::hellocm_msgs::InitResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hellocm_msgs::InitResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.cycletime);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hellocm_msgs::InitResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hellocm_msgs::InitResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "cycletime: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cycletime);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLOCM_MSGS_MESSAGE_INITRESPONSE_H
