// Generated by gencpp from file cmrosutils/CMRemoteResponse.msg
// DO NOT EDIT!


#ifndef CMROSUTILS_MESSAGE_CMREMOTERESPONSE_H
#define CMROSUTILS_MESSAGE_CMREMOTERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cmrosutils
{
template <class ContainerAllocator>
struct CMRemoteResponse_
{
  typedef CMRemoteResponse_<ContainerAllocator> Type;

  CMRemoteResponse_()
    : res(0)
    , msg()  {
    }
  CMRemoteResponse_(const ContainerAllocator& _alloc)
    : res(0)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _res_type;
  _res_type res;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CMRemoteResponse_

typedef ::cmrosutils::CMRemoteResponse_<std::allocator<void> > CMRemoteResponse;

typedef boost::shared_ptr< ::cmrosutils::CMRemoteResponse > CMRemoteResponsePtr;
typedef boost::shared_ptr< ::cmrosutils::CMRemoteResponse const> CMRemoteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cmrosutils::CMRemoteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cmrosutils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cf6b5d22125b6caef41ccf14f7c3348";
  }

  static const char* value(const ::cmrosutils::CMRemoteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cf6b5d22125b6caULL;
  static const uint64_t static_value2 = 0xef41ccf14f7c3348ULL;
};

template<class ContainerAllocator>
struct DataType< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cmrosutils/CMRemoteResponse";
  }

  static const char* value(const ::cmrosutils::CMRemoteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32  res\n\
string msg\n\
\n\
";
  }

  static const char* value(const ::cmrosutils::CMRemoteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CMRemoteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmrosutils::CMRemoteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cmrosutils::CMRemoteResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CMROSUTILS_MESSAGE_CMREMOTERESPONSE_H
